output "vpc_id" { value = aws_vpc.this.id }
output "vpc_cidr" { value = aws_vpc.this.cidr_block }
output "public_subnet_ids" { value = aws_subnet.public[*].id }
output "private_subnet_ids" { value = aws_subnet.private[*].id }
output "isolated_subnet_ids" { value = aws_subnet.isolated[*].id }
output "public_route_table_id" { value = aws_route_table.public.id }
output "private_route_table_id" { value = aws_route_table.private.id }
output "isolated_route_table_id" { value = aws_route_table.isolated.id }
output "nat_gateway_id" { value = var.enable_nat_gateway ? aws_nat_gateway.this[0].id : null }
output "s3_endpoint_id" { value = var.enable_s3_endpoint ? aws_vpc_endpoint.s3[0].id : null }
